application: minyattra
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

handlers:

######################### REST ENDPOINTS #########################
- url: /api/members/.*
  script: handlers.rest.users.app
  secure: always

######################### STATIC ENDPOINTS #########################
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/img
  static_dir: assets/img

- url: /assets/fonts
  static_dir: assets/fonts

- url: /assets/scss
  static_dir: assets/scss

######################### WEB ENDPOINTS #########################
- url: /member/.*
  script: handlers.web.add_member.app
  secure: always

- url: /users/.*
  script: handlers.web.auth.app
  secure: always

- url: /add_company
  script: handlers.web.add_member.app
  secure: always

- url: /.*
  script: handlers.web.index.app
  secure: always

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'