application: minyattra
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

handlers:

######################### REST ENDPOINTS #########################
- url: /api/members/.*
  script: handlers.rest.users.app

- url: /api/startups/.*
  script: handlers.rest.startups.app

- url: /api/projects/.*
  script: handlers.rest.projects.app

- url: /api/common/.*
  script: handlers.rest.common.app

######################### STATIC ENDPOINTS #########################
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/img
  static_dir: assets/img

- url: /assets/fonts
  static_dir: assets/fonts

- url: /assets/scss
  static_dir: assets/scss

- url: /assets
  static_dir: assets

- url: /favicon\.ico
  mime_type: image/png
  static_files: assets/img/favicon.png
  upload: assets/img/favicon\.png

######################### WEB ENDPOINTS #########################
- url: /temp.*
  script: handlers.web.temp.app

- url: /member/.*
  script: handlers.web.add_member.app

- url: /users/.*/login_callback
  script: handlers.web.login_auth.app

- url: /users/login_success
  script: handlers.web.login_auth.app

- url: /users/handle_custom_login
  script: handlers.web.login_auth.app

- url: /users/confirm_email
  script: handlers.web.login_auth.app

- url: /users/handle_verify_email
  script: handlers.web.login_auth.app

- url: /users/.*
  script: handlers.web.auth.app

- url: /surveys/.*
  script: handlers.web.surveys.app

- url: /add_company
  script: handlers.web.add_member.app

- url: /startups.*
  script: handlers.web.startups.app

- url: /projects.*
  script: handlers.web.projects.app

- url: /.*
  script: handlers.web.index.app

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'