application: minyattra
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

handlers:

######################### REST ENDPOINTS #########################

######################### STATIC ENDPOINTS #########################
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/img
  static_dir: assets/img

- url: /assets/fonts
  static_dir: assets/fonts

- url: /assets/scss
  static_dir: assets/scss

######################### WEB ENDPOINTS #########################
- url: /.*
  script: handlers.web.index.app

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'