RESPONSE_TYPE = 'code'
CLIENT_ID = '75roiql0j3mfv4'
CLIENT_SECRET ='LeW9ypga1UdUo5Ix'
AUTHORIZATION_URL = 'https://www.linkedin.com/uas/oauth2/authorization'
SCOPE = 'r_fullprofile'
STATE = 'karnatakanammarajya'
REDIRECT_URI = 'http://minyattra.appspot.com/users/handle_linkedin_auth'
ACCESS_TOKEN_URL = 'https://www.linkedin.com/uas/oauth2/accessToken'
GRANT_TYPE = 'authorization_code'
PROFILE_URL = 'https://api.linkedin.com/v1/people/~:(%s)?format=json&oauth2_access_token=%s'